config/routes.rb
Burokompotov::Application.routes.draw do
  get "main/index"

  get "main/admin"

  resources :partitions

   root :to => 'main#index'

end

app/models/partition.rb
class Partition < ActiveRecord::Base
  attr_accessible :content, :foot, :head, :img, :is_close, :part, :pos, :title


  scope :visible, where("is_close != ?", true).order(:pos)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def admin
  end
end

app/controllers/partitions_controller.rb
class PartitionsController < ApplicationController
  # GET /partitions
  # GET /partitions.json
  def index
    @partitions = Partition.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @partitions }
    end
  end

  # GET /partitions/1
  # GET /partitions/1.json
  def show
    @partition = Partition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @partition }
    end
  end

  # GET /partitions/new
  # GET /partitions/new.json
  def new
    @partition = Partition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @partition }
    end
  end

  # GET /partitions/1/edit
  def edit
    @partition = Partition.find(params[:id])
  end

  # POST /partitions
  # POST /partitions.json
  def create
    @partition = Partition.new(params[:partition])

    respond_to do |format|
      if @partition.save
        format.html { redirect_to @partition, notice: 'Partition was successfully created.' }
        format.json { render json: @partition, status: :created, location: @partition }
      else
        format.html { render action: "new" }
        format.json { render json: @partition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /partitions/1
  # PUT /partitions/1.json
  def update
    @partition = Partition.find(params[:id])

    respond_to do |format|
      if @partition.update_attributes(params[:partition])
        format.html { redirect_to @partition, notice: 'Partition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @partition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partitions/1
  # DELETE /partitions/1.json
  def destroy
    @partition = Partition.find(params[:id])
    @partition.destroy

    respond_to do |format|
      format.html { redirect_to partitions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/partitions_helper.rb
module PartitionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Burokompotov" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= stylesheet_link_tag    "main", :media => "all" %>
    <%= javascript_include_tag "application" %>

  </head>
  <body>

    <div class="navbar navbar-static-top">
      <div class="navbar-inner">
        <div class="container">

<%= image_tag "logo.jpg"  %> <span class="phone">+7 (921) 933 98 37</span>
        </div>

   <div id="myCarousel" class="carousel slide">
    <!-- Carousel items -->
    <div class="carousel-inner">
      <div class="active item"><%= image_tag "slide1.gif"  %> </div>
      <div class="item"><%= image_tag "slide2.gif"  %></div>
      <div class="item"><%= image_tag "slide3.gif"  %></div>
    </div>
    <!-- Carousel nav -->
    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
   </div>


<%= render "main/top_menu" %>

      </div>
    </div>

 <div class="container">


        <%= yield %>


      <footer>
        <p>&copy; Бюро компотов, 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/partition.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Burokompotov" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

 <div class="navbar navbar-inverse navbar-fixed-top">
<div class="navbar-inner">
<div class="container">
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</a>
<a class="brand" href="#">Project name</a>
<div class="nav-collapse collapse">
<ul class="nav">
<li class="active"><a href="#">Home</a></li>
<li><a href="#about">About</a></li>
<li><a href="#contact">Contact</a></li>
<li class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
<ul class="dropdown-menu">
<li><a href="#">Action</a></li>
<li><a href="#">Another action</a></li>
<li><a href="#">Something else here</a></li>
<li class="divider"></li>
<li class="nav-header">Nav header</li>
<li><a href="#">Separated link</a></li>
<li><a href="#">One more separated link</a></li>
</ul>
</li>
</ul>
<form class="navbar-form pull-right">
<input class="span2" type="text" placeholder="Email">
<input class="span2" type="password" placeholder="Password">
<button type="submit" class="btn">Sign in</button>
</form>
</div>
</div>
</div>
</div>
<div class="container">

<div class="hero-unit">
<h1>Hello, world!</h1>
<p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
<p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
            <div class="span9">

            <%= bootstrap_flash %>
            <%= yield %>
          </div>
<div class="span4">
<h2>Heading</h2>
<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
<p><a class="btn" href="#">View details &raquo;</a></p>
</div>
<div class="span4">
<h2>Heading</h2>
<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
<p><a class="btn" href="#">View details &raquo;</a></p>
</div>
<div class="span4">
<h2>Heading</h2>
<p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
<p><a class="btn" href="#">View details &raquo;</a></p>
</div>
</div>

<footer>
<p>&copy; Company 2012</p>
</footer>
</div>

  </body>
</html>

app/views/main/_top_menu.erb
<div class="container nav-collapse" >
  <ul class="nav">
    <% Partition.visible.each  do |part| %>
       <li><%= link_to part.head, partitions_path  %></li>
    <% end %>
  </ul>
</div><!--/.nav-collapse -->

app/views/main/admin.html.erb
<h1>Main#admin</h1>
<p>Find me in app/views/main/admin.html.erb</p>


<%= nav_bar :fixed => :top, :brand => "Fashionable Clicheizr 2.0", :responsive => true do %>
    <%= menu_group do %>
        <%= menu_item "Home", root_path %>
        <%= menu_divider %>
        <%= drop_down "Products" do %>
            <%= menu_item "Things you can't afford", '' %>
            <%= menu_item "Things that won't suit you anyway", '' %>
            <%= menu_item "Things you're not even cool enough to buy anyway", '' %>
            <%# if current_user.lives_in_hackney? %>
                <%#= menu_item "Bikes", '' %>
            <%# end %>
        <% end %>
        <%= menu_item "About Us", '' %>
        <%= menu_item "Contact", '' %>
    <% end %>
    <%= menu_group :pull => :right do %>
        <%# if current_user %>
            <%#= menu_item "Log Out", '' %>
        <%# else %>
            <%#= form_for @user, :url => session_path(:user), html => {:class=> "navbar-form pull-right"} do |f| -%>
            <%#= form_tag  :url => 'session_path(:user)', html => {:class=> "navbar-form pull-right"} do  -%>
              <p><%= text_field_tag :email %></p>
              <p><%= password_field_tag :password %></p>
              <p><%= submit_tag "Sign in" %></p>
            <%# end -%>
        <%# end %>
    <% end %>
<% end %>

          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->

app/views/partitions/_form.html.erb
<%= form_for(@partition) do |f| %>
  <% if @partition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@partition.errors.count, "error") %> prohibited this partition from being saved:</h2>

      <ul>
      <% @partition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :img %><br />
    <%= f.text_field :img %>
  </div>
  <div class="field">
    <%= f.label :head %><br />
    <%= f.text_area :head %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :foot %><br />
    <%= f.text_area :foot %>
  </div>
  <div class="field">
    <%= f.label :part %><br />
    <%= f.text_field :part %>
  </div>
  <div class="field">
    <%= f.label :is_close %><br />
    <%= f.check_box :is_close %>
  </div>
  <div class="field">
    <%= f.label :pos %><br />
    <%= f.number_field :pos %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/partitions/edit.html.erb
<h1>Editing partition</h1>

<%= render 'form' %>

<%= link_to 'Show', @partition %> |
<%= link_to 'Back', partitions_path %>

app/views/partitions/index.html.erb
<h1>Listing partitions</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Img</th>
    <th>Head</th>
    <th>Content</th>
    <th>Foot</th>
    <th>Part</th>
    <th>Is close</th>
    <th>Pos</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @partitions.each do |partition| %>
  <tr>
    <td><%= partition.title %></td>
    <td><%= partition.img %></td>
    <td><%= partition.head %></td>
    <td><%= partition.content %></td>
    <td><%= partition.foot %></td>
    <td><%= partition.part %></td>
    <td><%= partition.is_close %></td>
    <td><%= partition.pos %></td>
    <td><%= link_to 'Show', partition %></td>
    <td><%= link_to 'Edit', edit_partition_path(partition) %></td>
    <td><%= link_to 'Destroy', partition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Partition', new_partition_path %>

app/views/partitions/new.html.erb
<h1>New partition</h1>

<%= render 'form' %>

<%= link_to 'Back', partitions_path %>

app/views/partitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @partition.title %>
</p>

<p>
  <b>Img:</b>
  <%= @partition.img %>
</p>

<p>
  <b>Head:</b>
  <%= @partition.head %>
</p>

<p>
  <b>Content:</b>
  <%= @partition.content %>
</p>

<p>
  <b>Foot:</b>
  <%= @partition.foot %>
</p>

<p>
  <b>Part:</b>
  <%= @partition.part %>
</p>

<p>
  <b>Is close:</b>
  <%= @partition.is_close %>
</p>

<p>
  <b>Pos:</b>
  <%= @partition.pos %>
</p>


<%= link_to 'Edit', edit_partition_path(@partition) %> |
<%= link_to 'Back', partitions_path %>